### ISSUE TITLE
Documentation: Consider full TOC on Left.

### ISSUE THREAD

**Issue by antone405** [monk-io/docs#9]
One thing noted was how you must be "into a process" to find certain documentation. For example, a user may need to go through the "Chainlink Nodes" example before finding info on [CI/CD](https://docs.monk.io/guides/ci-cd/) options.

The "Hamburger" nav is good but having an expanded TOC would be easier to jump to the area needed.

**Comment by antone405** [comment]
Example: [JFrog Documentation](https://www.jfrog.com/confluence/display/JFROG/)

**Comment by nooga** [comment]
![Screenshot 2021-05-11 at 15 07 53](https://user-images.githubusercontent.com/198496/117820269-ab96db00-b26a-11eb-83e2-b5de633951f5.png)

@antone405 this is how the site looks for me. The hamburger shows up on mobile and narrow browser windows.

**Comment by nooga** [comment]
Fixed by #12
